/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pacificinstitute;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

/**
 *
 * @author Valentina
 */
public class VentanaTutor extends javax.swing.JFrame {

    ArrayList<Tutor> listaTutores = new ArrayList<Tutor>();
    /** Creates new form VentanaTutor */
    public VentanaTutor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblRut = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        lblCertificado = new javax.swing.JLabel();
        rBtnSi = new javax.swing.JRadioButton();
        rBtnNo = new javax.swing.JRadioButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTutores = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setText("Nombre");

        lblApellido.setText("Apellido");

        lblRut.setText("Rut");

        lblCertificado.setText("Esta certificado?");

        buttonGroup1.add(rBtnSi);
        rBtnSi.setText("Si");

        buttonGroup1.add(rBtnNo);
        rBtnNo.setText("No");
        rBtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnNoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        tblTutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTutores);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCertificado)
                        .addGap(18, 18, 18)
                        .addComponent(rBtnSi)
                        .addGap(18, 18, 18)
                        .addComponent(rBtnNo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblApellido)
                            .addComponent(lblRut))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtApellido)
                            .addComponent(txtRut))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblApellido)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRut)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCertificado)
                            .addComponent(rBtnSi)
                            .addComponent(rBtnNo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnBuscar)
                            .addComponent(btnAgregar)
                            .addComponent(btnListar)
                            .addComponent(btnActualizar))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver)
                        .addContainerGap(17, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rBtnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnNoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        int rut = Integer.parseInt(txtRut.getText());
        boolean isCertificated = false;
        
        //Si esta seleccionado Si isCertificated es igual a true de lo contrario sigue como false
        if (rBtnSi.isSelected()) {
            isCertificated = true;
        }
        
         if (!"".equals(nombre) && !"".equals(apellido) && !"".equals(rut)) {
            Tutor tutor = new Tutor (nombre,rut, apellido, isCertificated);
            Conexion conexion = new Conexion();
            Connection con = conexion.getConexion();
            try {
                PreparedStatement ps = con.prepareStatement("insert into tutores (Rut, Nombre, Apellido, isCertificated) values(?,?,?,?)");
                ps.setInt(1, tutor.getRut());
                ps.setString(2, tutor.getNombre());
                ps.setString(3, tutor.getApellido());
                ps.setBoolean(4, tutor.isCertificated());
                int result = ps.executeUpdate();
                if (result > 0) {
                    cargarLista();
                    cargarDatosTabla();
                    limpiar();
                    JOptionPane.showMessageDialog(null, "Registro ha sido creado exitosamente");
                }else{
                    JOptionPane.showMessageDialog(null, "Registro no se ha creado");
                }
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(VentanaTutor.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
        else {
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos");
        }
       
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        int rut;
        rut = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el registro del tutor a eliminar"));
       
        Conexion conexion = new Conexion();
        Connection con = conexion.getConexion();

            try {
                PreparedStatement ps = con.prepareStatement("select * from tutores where rut = "+rut+" limit 1;");
                ResultSet rs = ps.executeQuery();


                if(rs.next()){

                    ps = (PreparedStatement) con.prepareStatement("DELETE FROM tutores WHERE Rut=?");
                    ps.setString(1, String.valueOf(rut));

                    int result = ps.executeUpdate();
                    if(result>0){
                        cargarLista();
                        cargarDatosTabla();  
                        JOptionPane.showMessageDialog(null, "Registro eliminado de manera exitosa");                            
                    }else {
                        JOptionPane.showMessageDialog(null, "No se ha podido eliminar el registro");
                    }
               }else{
                    JOptionPane.showMessageDialog(null, "No se ha encontrado el tutor con el rut: "+rut);
                }
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(VentanaTutor.class.getName()).log(Level.SEVERE, null, ex);
            }     
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       
        int rut;   
        rut = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el rut del tutor a buscar"));
        
        Conexion conexion = new Conexion();
        Connection con = conexion.getConexion();
        
        try {
            PreparedStatement ps = con.prepareStatement("select * from tutores where rut = "+rut+" limit 1;");
            ResultSet rs = ps.executeQuery();
            Tutor tutor;
            
            if(rs.next()){
                tutor = new Tutor(rs.getString(2), rs.getInt(1), rs.getString(3), rs.getBoolean(4));
                txtRut.setText(""+tutor.getRut());
                txtNombre.setText(tutor.getNombre());
                txtApellido.setText(tutor.getApellido());
                if (tutor.isCertificated()==true) {
                    rBtnSi.setSelected(true);
                }else {
                    rBtnNo.setSelected(true);
                }
                JOptionPane.showMessageDialog(null, tutor.mostrarDatos());
            }else{
                JOptionPane.showMessageDialog(null, "No se ha encontrado el tutor con el rut: "+rut);
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaTutor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        cargarLista();
        cargarDatosTabla();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        int rut = Integer.parseInt(txtRut.getText());
        boolean isCertificated = false;
        
        if (rBtnSi.isSelected()) {
            isCertificated = true;
        }
        
            if (!"".equals(nombre) && !"".equals(apellido) && !"".equals(rut)) {

                Tutor tutor = new Tutor (nombre,rut, apellido, isCertificated);
                Conexion conexion = new Conexion();
                Connection con = conexion.getConexion();

                try {
                    PreparedStatement ps = con.prepareStatement("select * from tutores where rut = "+rut+" limit 1;");
                    ResultSet rs = ps.executeQuery();


                    if(rs.next()){
                        ps = con.prepareStatement("update tutores set nombre=?, apellido=?, isCertificated=? where rut=?");

                        ps.setString(1, nombre);
                        ps.setString(2, apellido);
                        ps.setBoolean(3, isCertificated);
                        ps.setInt(4, rut);
                        int result = ps.executeUpdate();
                        if (result > 0) {
                            cargarLista();
                            cargarDatosTabla();
                            limpiar();
                            JOptionPane.showMessageDialog(null, "Registro ha sido actualizado");
                        }else{
                            JOptionPane.showMessageDialog(null, "Registro no se ha actualizado");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "No se ha encontrado el tutor con el rut: "+rut);
                    }
                    con.close();
                } catch (SQLException ex) {
                    Logger.getLogger(VentanaTutor.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }else {
                JOptionPane.showMessageDialog(null, "Debe completar todos los campos");
            }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
         this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    public void cargarDatosTabla(){
        
        String array[][] = null;
        
        if (listaTutores.size() > 0) {
            // Determina las dimensiones de la matriz de la tabla
            array = new String [listaTutores.size()][4];
            for (int i = 0; i < listaTutores.size(); i++) {
                
                array[i][0]= listaTutores.get(i).getNombre();
                array[i][1]= listaTutores.get(i).getApellido();
                array[i][2]= String.valueOf (listaTutores.get(i).getRut());
                array[i][3]= listaTutores.get(i).isCertificated() == true ? "Si" : "No";
                
                tblTutores.setModel(new javax.swing.table.DefaultTableModel(
                        array,
                        new String[]{
                            "Nombre","Apellido", "Rut","¿Certificado?"
                        }
                ));        
            }
        } else {
            tblTutores.setModel(new javax.swing.table.DefaultTableModel(
                    array,
                    new String[]{
                        "Nombre", "Apellidos", "Rut", "¿Certificado?"
                    }
            ));
        
        }
    
    }
    
    private void cargarLista(){
        Conexion conexion = new Conexion();
        Connection con = conexion.getConexion();
        try {
            PreparedStatement ps = con.prepareStatement("select * from tutores;");
            ResultSet rs = ps.executeQuery();
            Tutor tutor;
            listaTutores.clear();
            while(rs.next()){
                tutor = new Tutor(rs.getString(2), rs.getInt(1), rs.getString(3), rs.getBoolean(4));
                listaTutores.add(tutor);
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaTutor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
    public void limpiar (){
       txtNombre.setText("");
       txtApellido.setText("");
       txtRut.setText("");
       
       //txtNumRegistro.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCertificado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRut;
    private javax.swing.JRadioButton rBtnNo;
    private javax.swing.JRadioButton rBtnSi;
    private javax.swing.JTable tblTutores;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables

}
